name: Release
description: Release Action
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Fetch Git repository and checkout
      uses: 'actions/checkout@v4'

    - uses: actions/cache@v3
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

    - name: Build
      run: yarn build
      shell: bash

    - name: Dry Run Release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        NPM_TOKEN: ${{ inputs.github_token }}
      with:
        dry_run: true
        branches: |
          [
            'main',
          ]

    - name: Release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        NPM_TOKEN: ${{ inputs.github_token }}
      with:
        branches: |
          [
            'main',
          ]
