name: Integration Test
description: Integration Test Action
runs:
  using: 'composite'
  steps:
    - name: Fetch Git repository and checkout
      uses: 'actions/checkout@v4'

    - uses: actions/cache@v3
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

    - name: Setup Browser
      run: yarn playwright install
      shell: bash

    - name: Setup Browser Dependencies
      run: yarn playwright install-deps
      shell: bash

    - name: Integration Testing
      run: yarn test:integration
      shell: bash
