name: Dependabot Automerge Pull Requests
on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Setup
        uses: ./.github/actions/setup

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: 'actions/checkout@v4'
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Lint
        uses: ./.github/actions/lint

  unit-test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: 'actions/checkout@v4'
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Unit Test
        uses: ./.github/actions/unit-test

  integration-test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: 'actions/checkout@v4'
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Integration Test
        uses: ./.github/actions/integration-test

  coverage:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: 'actions/checkout@v4'
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Integration Test
        uses: ./.github/actions/coverage

  dependabot-automerge-prs:
    runs-on: ubuntu-latest
    needs:
      - lint
      - unit-test
      - integration-test
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: 'actions/checkout@v4'
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Merge Dependabot Pull Requests
        uses: fastify/github-action-merge-dependabot@v3
