name: Dependabot Automerge Pull Requests
on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Git repository and checkout
        uses: 'actions/checkout@v4'
      - name: Setup
        uses: ./.github/actions/setup

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Lint
        uses: ./.github/actions/lint

  unit-test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Unit Test
        uses: ./.github/actions/unit-test

  integration-test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Integration Test
        uses: ./.github/actions/integration-test

  dependabot-automerge-prs:
    runs-on: ubuntu-latest
    needs:
      - lint
      - unit-test
      - integration-test
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Merge Dependabot Pull Requests
        uses: fastify/github-action-merge-dependabot@v3
